name: E2E - Cypress

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Node + cache npm
      - name: Setup Node (com cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3) Instalar dependências
      - name: Install deps (clean)
        run: npm ci

      # 4) Subir servidor local
      - name: Start local server
        run: |
          npx http-server ./local_site -p 8080 -a 0.0.0.0 &
          npx wait-on http://127.0.0.1:8080

      # 5) Rodar Cypress (gera JUnit + Allure results)
      - name: Run Cypress (headless)
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: |
            npx cypress run \
              --config baseUrl=http://127.0.0.1:8080,retries=2,video=true

      # 6) Gerar relatório Allure (HTML) a partir de allure-results
      - name: Generate Allure Report
        if: always()
        run: |
          npx allure generate allure-results --clean -o allure-report
          # Opcional: gerar também um zip do relatório para download offline
          cd allure-report && zip -r ../allure-report.zip . && cd ..

      # 7) Upload do relatório Allure
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: |
            allure-report
            allure-report.zip
          if-no-files-found: ignore

      # 8) Upload JUnit (KPIs TMMi)
      - name: Upload JUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: results/*.xml
          if-no-files-found: ignore

      # 9) Upload screenshots se falhar
      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      # 10) Upload vídeos sempre (para análise)
      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
